server:
  port: 16003
spring:
  application:
    name: "consumer-service"
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#        server‐addr: 127.0.0.1:7777,127.0.0.1:8888,127.0.0.1:9999