services:
  mysql:
    image: 'mysql:latest'
    container_name: 'elm-springcloud-mysql'
    environment:
      - 'MYSQL_DATABASE=elm_springcloud'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=12345678'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
  nacos:
    image: 'nacos/nacos-server:v2.4.3'
    container_name: 'elm-springcloud-nacos'
    environment:
      - 'MODE=standalone'
    ports:
      - '8848:8848'
      - '9848:9848'